version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tinmu-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tinmu
      POSTGRES_PASSWORD: tinmu
      POSTGRES_DB: tinmu
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: